### PR TITLE
Relax httpoison requirement

### PR DESCRIPTION
**Pull request by coop**
This sets a minimum requirement for httpoison - currently it's at v1.5.

### CODE REVIEW

**Comment by coop** [comment]
@dmlittle I'm double checking that this actually works with httpoison 1.5. I'm currently getting an error:

```
==> lob_elixir
Compiling 12 files (.ex)
warning: type response/0 already exported
  lib/lob/client.ex:10


== Compilation error in file lib/lob/client.ex ==
** (CompileError) lib/lob/client.ex:10: type response() already defined
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
```

I need to double check by I think `response` is first defined in `HTTPoison.Base` and it's clashing with the type spec in `lob/client.ex`.

**Comment by coop** [comment]
Yeah - there is definitely an issue. Let me close this and sort it out. I'll submit another PR when it's OK.
